{
 "title": "Redis Monitoring",
 "description": "Redis Dashboard for Prometheus\n\nIf you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(redis_up,pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory "
    },
    {
     "expr": "redis_memory_used_peak_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Peak"
    },
    {
     "expr": "redis_memory_used_lua_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Lua"
    },
    {
     "expr": "redis_memory_used_dataset_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Dataset"
    },
    {
     "expr": "redis_memory_used_overhead_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Overhead"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory Rss"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "description": "dd:hh:mm:ss",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redis Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{redis_version}}"
    }
   ]
  },
  {
   "title": "Ops/sec[3m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{instance=\"$instance\"}[3m])/180"
    }
   ]
  },
  {
   "title": "Number of keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Is linked to master replication",
   "type": "stat",
   "description": "If it shows no/nothing then means that node can be down and replication does not working",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_master_link_up{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maxmemory Policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{maxmemory_policy}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Processed total "
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])   / (rate(redis_keyspace_misses_total{instance=\"$instance\"}[5m]) + rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])) ",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db) > 0",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum (redis_db_keys{instance=~\"$instance\"}) by (db)- sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (db)) > 0",
     "legendFormat": "Not expiring {{db}}"
    },
    {
     "expr": "(sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (db)) > 0",
     "legendFormat": "Expiring {{db}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted [5 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Input bytes {{ pod }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Output bytes {{ pod }}"
    }
   ]
  },
  {
   "title": "Connections usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "Active Clients"
    },
    {
     "expr": "redis_config_maxclients{instance=\"$instance\"}",
     "legendFormat": "Max Clients"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(redis_commands_total{instance=~\"$instance\"} [1m]) >0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=\"$instance\"}[5m])) / sum(rate(redis_commands_processed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (rate(redis_cpu_sys_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_sys_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "System"
    },
    {
     "expr": "100 * (rate(redis_cpu_user_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_user_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "description": "Total Time Spent by Command / sec",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[2m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average TTL for db",
   "type": "timeseries",
   "description": "Includes only not eternal database (TTL set to 0)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{instance=~\"$instance\"} >0",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Redis memory usage trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected slave lag/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_connected_slave_lag_seconds{}",
     "legendFormat": "Slave IP: {{slave_ip}}:{{slave_port}}"
    }
   ]
  }
 ]
}